name: checkout-action
description: GitHub Action for checking out a repository. (Simplified actions/checkout alternative that does not depend on Node.js.)
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}

  persist-credentials:
    description: 'Whether to configure the token or SSH key with the local git config'
    default: true
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
    default: 1

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
      env:
        INPUT_TOKEN: '${{ inputs.token }}'
        INPUT_PERSIST_CREDENTIALS: '${{ inputs.persist-credentials }}'
        INPUT_FETCH_DEPTH: '${{ inputs.fetch-depth }}'
      shell: bash
